build:
  properties: skipTests skipDepClean
clients:
  - repository: SpoonLabs/flacoco
  - repository: SpoonLabs/coming
  - repository: SpoonLabs/astor
  - repository: SpoonLabs/npefix
  - repository: SpoonLabs/nopol
    sources: nopol/src/main/java
  - repository: SpoonLabs/npefix
  - repository: STAMP-project/AssertFixer
  - repository: Spirals-Team/casper
  - repository: SpoonLabs/CoCoSpoon
  - repository: STAMP-project/dspot
    sources: dspot/src/main/java
  - repository: SpoonLabs/gumtree-spoon-ast-diff
  - repository: Spirals-Team/jPerturb
  - repository: SpoonLabs/metamutator
  - repository: SpoonLabs/spooet
  - repository: KTH/spork
